### ISSUE TITLE
Highradius Source Code Data Leakage | Action Needed ASAP

### ISSUE THREAD

**Issue by Ranjit-Chigurupati** [yuvrajverma01/highradiusproj#1]
Hi yuvrajverma01,

We identified that one of your GitHub public Repositories “[highradiusproj](https://github.com/yuvrajverma01/highradiusproj)contains a source code which is related/owned by the Highradius. Please Delete/remove the respective data from the public exposure, if not this will be considered as a Copyright Violation and necessary action will be taken.

Any data that is related/owned by the Highradius Corporation should not be used for your personal benefits or should not exposed in to the public. Any such unauthorized activities will be considered as series offence and necessary legal actions will be taken.

Thanks & Regards,
Ranjit Kumar Chigurupati,
Led Information Security Engineer,
Highradius Corporation.

**Comment by yuvrajverma01** [comment]
Sure Ranjit, I'll delete this but just so you know that this repo didn’t even have a single line of code. I appeared for the high radius project and it's just the name. Well I'll delete it no issues but I didn’t knew empty repos can be a violation too.
